#!/bin/bash
set -e

#Ensure in scripts directory
cd $( dirname "${BASH_SOURCE[0]}" )/..

if [[ -z "${HOST}" ]]; then
    HOST=doorbell-pi
fi

echo "Host: $HOST"

echo "Stopping service..."
RESULT=$(ssh $HOST "supervisorctl stop doorbell-pi")
if [[ $RESULT = *"ERROR"* ]]; then
    echo "Error stopping service! - $RESULT"
    exit -1
fi

echo "Copying files..."
rsync -ah --progress --delete --exclude-from="$(git -C . ls-files --exclude-standard -oi --directory >.git/ignores.tmp && echo .git/ignores.tmp)" . $HOST:/srv/doorbell-pi

echo "Starting service..."
RESULT=$(ssh $HOST "supervisorctl start doorbell-pi")
if [[ $RESULT = *"ERROR"* ]]; then
    echo "Error starting service! - $RESULT"
    exit -1
fi

exit 0