#!/bin/bash
set -e

#Ensure in scripts directory
cd $( dirname "${BASH_SOURCE[0]}" )/..

echo "Stopping service..."
RESULT=$(ssh doorbell-pi "supervisorctl stop doorbell-pi")
if [[ $RESULT = *"ERROR"* ]]; then
    echo "Error stopping service! - $RESULT"
    exit -1
fi

echo "Copying files..."
rsync -ah --progress --delete --include .git --exclude-from="$(git -C . ls-files --exclude-standard -oi --directory >.git/ignores.tmp && echo .git/ignores.tmp)" . doorbell-pi:/srv/doorbell-pi

echo "Starting service..."
RESULT=$(ssh doorbell-pi "supervisorctl start doorbell-pi")
if [[ $RESULT = *"ERROR"* ]]; then
    echo "Error stopping service! - $RESULT"
    exit -1
fi

exit 0