#!/bin/bash
set -e

#Ensure in scripts directory
cd $( dirname "${BASH_SOURCE[0]}" )/..


echo "Activiating venv"
source ~/.venv/doorbell-pi/bin/activate

echo "Starting service"
exec python -m doorbell
