#!/bin/bash
set -e

#Ensure in scripts directory
cd $( dirname "${BASH_SOURCE[0]}" )/..


echo "Activiating venv"
source ~/.venv/doorbell-pi/bin/activate

#echo "Installing requirements"
#pip install -r requirements.txt

echo "Starting service"
exec python -m doorbell
